[package]
name = "mcrl3_gui"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
mcrl3_utilities.workspace = true

clap.workspace = true
log.workspace = true
streaming-iterator.workspace = true
winapi.workspace = true
