# This is a template cbindgen.toml file with all of the default values.
# Some values are commented out because their absence is the real default.
#
# See https://github.com/mozilla/cbindgen/blob/master/docs.md#cbindgentoml
# for detailed documentation of every option here.


# The language for which to generate bindings for.
language = "C++"

# The namespace to use
namespaces = ["merc", "ffi"]

# Use include guards.
include_guard = "MERC_FFI_H"