[package]
name = "merc_sabre-ffi"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[features]
import = []

[dependencies]
merc_aterm.workspace = true
merc_data.workspace = true
merc_utilities.workspace = true
merc_unsafety.workspace = true