[package]
name = "merc_number"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
merc_utilities.workspace = true

rand.workspace = true
bitstream-io.workspace = true
num.workspace = true