name: Benchmark

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9
      
    - name: Checkout the repository
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Run aterm Benchmarks
      run: cargo bench -p benchmarks_aterm
      env:
        RUSTC_WRAPPER: sccache

    - name: Run ldd Benchmarks
      run: cargo bench -p benchmarks_ldd
      env:
        RUSTC_WRAPPER: sccache

    - name: Run sabre Benchmarks
      run: cargo bench -p benchmarks_sabre
      env:
        RUSTC_WRAPPER: sccache

    - name: Run sharedmutex Benchmarks
      run: cargo bench -p benchmarks_sharedmutex
      env:
        RUSTC_WRAPPER: sccache
        
    - name: Run GUI Benchmarks
      run: cargo bench -p benchmarks_ltsgraph
      working-directory: tools/gui/
      env:
        RUSTC_WRAPPER: sccache
