name: Benchmark

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  benchmark:
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9
      
    - name: Checkout the repository
      uses: actions/checkout@v6
      with:
        submodules: true

    - name: Build aterm Benchmarks
      run: cargo build -p benchmarks_aterm --release
      env:
        RUSTC_WRAPPER: sccache

    - name: Build ldd Benchmarks
      run: cargo build -p benchmarks_ldd --release
      env:
        RUSTC_WRAPPER: sccache

    - name: Build sabre Benchmarks
      run: cargo build -p benchmarks_sabre --release
      env:
        RUSTC_WRAPPER: sccache

    - name: Build sharedmutex Benchmarks
      run: cargo build -p benchmarks_sharedmutex --release
      env:
        RUSTC_WRAPPER: sccache
        
    - name: Build GUI Benchmarks
      run: cargo build -p benchmarks_ltsgraph --release
      working-directory: tools/gui/
      env:
        RUSTC_WRAPPER: sccache
