name: Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always
  SCCACHE_GHA_ENABLED: on

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:      
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:    
    - name: Install Ubuntu Dependencies
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: libfontconfig1-dev, libfreetype6-dev
        version: 1.0
      if: matrix.os == 'ubuntu-latest'

    - name: Setup sccache
      uses: mozilla-actions/sccache-action@v0.0.9

    - name: Install stable rust
      uses: dtolnay/rust-toolchain@stable
      
    - name: Install nextest
      uses: taiki-e/install-action@nextest
      
    - name: Checkout the repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Run tests
      run: cargo nextest run --no-fail-fast -- --include-ignored
      env:
        RUST_BACKTRACE: full
        RUST_LOG: debug
        RUSTC_WRAPPER: sccache

    - name: Run mCRL2 tests
      run: |
        cd tools/mcrl2
        cargo nextest run --no-fail-fast -- --include-ignored
      env:
        RUST_BACKTRACE: full
        RUST_LOG: debug
        RUSTC_WRAPPER: sccache
      
    - name: Run GUI tests
      run: |
        cd tools/gui
        cargo nextest run --no-fail-fast -- --include-ignored
      env:
        RUST_BACKTRACE: full
        RUST_LOG: debug
        RUSTC_WRAPPER: sccache
